# Q1. Write a Python code to implement the KNN classifier algorithm on load_iris dataset in sklearn.datasets.

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
from sklearn.datasets import load_iris
data = load_iris()

In [11]:
df = pd.DataFrame(data.data, columns=data.feature_names)

In [12]:
df['target'] = data.target

In [13]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [23]:
#independent features
X=df.iloc[:,:-1]
#dependent features
y=df.iloc[:,-1]

In [33]:
X.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [28]:
from sklearn.neighbors import KNeighborsClassifier

In [29]:
classifier=KNeighborsClassifier(n_neighbors=5,algorithm='auto')
classifier.fit(X_train,y_train)

KNeighborsClassifier()

In [30]:
y_pred=classifier.predict(X_test)

In [31]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [32]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[19  0  0]
 [ 0 15  1]
 [ 0  0 15]]
0.98
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.94      0.97        16
           2       0.94      1.00      0.97        15

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



# Q2. Write a Python code to implement the KNN regressor algorithm on load_boston dataset in sklearn.datasets.

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [ ]:
'''`load_boston` has been removed from scikit-learn since version 1.2. 
But this is the example code for understanding.'''

from sklearn.datasets import load_boston
data = load_boston()

In [ ]:
df = pd.DataFrame(data.data, columns=data.feature_names)

In [ ]:
df['target'] = data.target

In [ ]:
#independent features
X=df.iloc[:,:-1]
#dependent features
y=df.iloc[:,-1]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [ ]:
from sklearn.neighbors import KNeighborsRegressor

In [ ]:
regressor = KNeighborsRegressor(n_neighbors=5,algorithm='auto')
regressor.fit(X_train,y_train)

In [ ]:
y_pred=regressor.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [ ]:
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))

# Q3. Write a Python code snippet to find the optimal value of K for the KNN classifier algorithm using cross-validation on load_iris dataset in sklearn.datasets.

In [35]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier

# Load the iris dataset
data = load_iris()
X = data.data
y = data.target

# Define a range of K values to test
k_values = range(1, 21)

# Perform cross-validation for each K value
mean_scores = []
for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    scores = cross_val_score(knn, X, y, cv=5)
    mean_scores.append(scores.mean())

# Find the optimal K value with the highest mean score
optimal_k = k_values[np.argmax(mean_scores)]
print("Optimal K value:", optimal_k)


Optimal K value: 6


# Q4. Implement the KNN regressor algorithm with feature scaling on load_boston dataset in sklearn.datasets.

In [ ]:
import numpy as np
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

'''`load_boston` has been removed from scikit-learn since version 1.2. 
But this is the example code for understanding.'''

# Load the Boston dataset
data = load_boston()
X = data.data
y = data.target

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Perform feature scaling using StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Create and fit the KNN regressor model
knn_regressor = KNeighborsRegressor(n_neighbors=5)
knn_regressor.fit(X_train_scaled, y_train)

# Make predictions on the test set
y_pred = knn_regressor.predict(X_test_scaled)

# Calculate mean squared error and R-squared score
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("R-squared Score:", r2)


# Q5. Write a Python code snippet to implement the KNN classifier algorithm with weighted voting on load_iris dataset in sklearn.datasets.

In [40]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier


# Load the iris dataset
data = load_iris()
X = data.data
y = data.target

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and fit the KNN regressor model
knn_classifier = KNeighborsClassifier(n_neighbors=5, weights='uniform')
knn_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = knn_classifier.predict(X_test)

from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



# Q6. Implement a function to standardise the features before applying KNN classifier.

In [42]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler


# Load the Iris dataset
data = load_iris()
X = data.data
y = data.target

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=33)

# Perform feature scaling using StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Create and fit the KNN regressor model
knn_classifier = KNeighborsClassifier(n_neighbors=6)
knn_classifier.fit(X_train_scaled, y_train)

# Make predictions on the test set
y_pred = knn_classifier.predict(X_test_scaled)

from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[ 8  0  0]
 [ 0 11  4]
 [ 0  0 15]]
0.8947368421052632
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      0.73      0.85        15
           2       0.79      1.00      0.88        15

    accuracy                           0.89        38
   macro avg       0.93      0.91      0.91        38
weighted avg       0.92      0.89      0.89        38



# Q7. Write a Python function to calculate the euclidean distance between two points.

In [43]:
import numpy as np

def euclidean_distance(point1, point2):
    """
    Calculate the Euclidean distance between two points.

    Parameters:
    - point1: list or array-like object representing the coordinates of the first point
    - point2: list or array-like object representing the coordinates of the second point

    Returns:
    - distance: float, the Euclidean distance between the two points
    """
    point1 = np.array(point1)
    point2 = np.array(point2)
    
    distance = np.sqrt(np.sum((point1 - point2) ** 2))
    
    return distance


In [45]:
point1 = [5,3,2]
point2 = [1,2,3]

distance = euclidean_distance(point1, point2)
print("Euclidean distance:", distance)

Euclidean distance: 4.242640687119285


# Q8. Write a Python function to calculate the manhattan distance between two points.

In [46]:
import numpy as np

def manhattan_distance(point1, point2):
    """
    Calculate the Manhattan distance between two points.

    Parameters:
    - point1: list or array-like object representing the coordinates of the first point
    - point2: list or array-like object representing the coordinates of the second point

    Returns:
    - distance: float, the Manhattan distance between the two points
    """
    point1 = np.array(point1)
    point2 = np.array(point2)
    
    distance = np.sum(np.abs(point1 - point2))
    
    return distance


In [47]:
point1 = [1, 2, 3]
point2 = [4, 5, 6]

distance = manhattan_distance(point1, point2)
print("Manhattan distance:", distance)


Manhattan distance: 9
